-- drop tables
DROP TABLE uzivatel;
DROP TABLE ubytovani;
DROP TABLE rezervace;
DROP TABLE doporuceni;

--DROP TABLE pronajimatel;
--DROP TABLE host;
--DROP TABLE pobyt;
--DROP TABLE recenze;
--DROP TABLE obdobi;


-- create tables
CREATE TABLE uzivatel (
	ucet_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	jmeno VARCHAR(255) NOT NULL,
	projemni VARCHAR(255) NOT NULL,
	RC INT NOT NULL,
	adresa VARCHAR(255) NOT NULL,
	telefon INT NOT NULL
);

CREATE TABLE ubytovani (
	ubytovani_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	typ VARCHAR(255) NOT NULL,
	cena INT, 
	typ_slevy VARCHAR(255),
	zeme VARCHAR(255) NOT NULL,
	mesto VARCHAR(255) NOT NULL,
	popis VARCHAR(255),
	vybaveni VARCHAR(255) NOT NULL,
	pravidla VARCHAR(255),
	bezpecnostni_prvky VARCHAR(255)
);

CREATE TABLE rezervace (
	ubytovani_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	suma INT NOT NULL,
	datum VARCHAR(255) NOT NULL
);

CREATE TABLE doporuceni (
	ubytovani_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	pamatky VARCHAR(255),
	aktivity VARCHAR(255),
	restaurace VARCHAR(255),
	autopujcovny VARCHAR(255)
);

