-- drop tables
DROP TABLE doporuceni;
DROP TABLE pobyt;
DROP TABLE recenze;
DROP TABLE pronajimatel;
DROP TABLE host;
DROP TABLE obdobi;
DROP TABLE rezervace;
DROP TABLE ubytovani;
DROP TABLE uzivatel;

-- create tables
CREATE TABLE uzivatel (
	ucet_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	jmeno VARCHAR(255) NOT NULL,
	projemni VARCHAR(255) NOT NULL,
	RC INT NOT NULL,
	adresa VARCHAR(255) NOT NULL,
	telefon INT NOT NULL
);

CREATE TABLE ubytovani (
	ubytovani_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	typ VARCHAR(255) NOT NULL,
	cena INT, 
	typ_slevy VARCHAR(255),
	zeme VARCHAR(255) NOT NULL,
	mesto VARCHAR(255) NOT NULL,
	popis VARCHAR(255),
	vybaveni VARCHAR(255) NOT NULL,
	pravidla VARCHAR(255),
	bezpecnostni_prvky VARCHAR(255)
);

CREATE TABLE rezervace (
	rezervace_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	suma INT NOT NULL,
	datum DATE NOT NULL
);

CREATE TABLE doporuceni (
	doporuceni_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	pamatky VARCHAR(255),
	aktivity VARCHAR(255),
	restaurace VARCHAR(255),
	autopujcovny VARCHAR(255)
);

CREATE TABLE host (
	uzivatel INT REFERENCES uzivatel ON DELETE CASCADE, 
	datum_registrace DATE NOT NULL,
	pocet_ubytovani INT,
	overeny_uzivatel VARCHAR(3) NOT NULL	
);

CREATE TABLE pronajimatel(
	uzivatel INT REFERENCES uzivatel ON DELETE CASCADE,
	informace VARCHAR(255) NOT NULL,
	reputace VARCHAR(255),
	cas_odezvy INT,
	foto VARCHAR(255)
);

CREATE TABLE pobyt (
	pobyt_num INT REFERENCES uzivatel ON DELETE CASCADE,
	datum_od DATE NOT NULL,
	datum_do DATE NOT NULL,
	platba VARCHAR(255),
	uskutosnil_se VARCHAR(3)
);

CREATE TABLE recenze (
	pobyt_num INT REFERENCES ubytovani ON DELETE CASCADE,
	komentar VARCHAR(255),
	hodnoceni INT
);

CREATE TABLE obdobi (
	id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,

	datum_od DATE not NULL,
	datum_do DATE not NULL,
	sleva int,
	
	rezervace_num NOT NULL,
 	ubytovani_num NOT NULL,

  	FOREIGN KEY (rezervace_num) REFERENCES rezervace(rezervace_id),
  	FOREIGN KEY (ubytovani_num) REFERENCES ubytovani(ubytovani_id)
)