/*
-- clear table to prevent duplicate values
DELETE FROM uzivatel ;
DELETE FROM host ;
DELETE FROM pronajimatel ;
DELETE FROM ubytovani;


-- INITILIZE VALUES

-- insert into uzivatel
INSERT INTO uzivatel VALUES (DEFAULT, 'Jan', 'Novák','100403001', 'Mlynská 12 Praha', '4206969696969');
INSERT INTO uzivatel VALUES (DEFAULT, 'Milan', 'Suchý','9109120009', 'Družstevná 125 Michalovce', '42055555555');
INSERT INTO uzivatel VALUES (DEFAULT, 'Peter', 'Dvořák','7704260080', 'Zimná 444 Bratislava', '421353696787');
INSERT INTO uzivatel VALUES (DEFAULT, 'Igor', 'Mokrý','6408140079', 'Športová 123 Košice', '421747585212');

INSERT INTO uzivatel VALUES (DEFAULT, 'Oleg', 'Starý','520606007', 'Lesná 665 Letanovce', '421555222555');
INSERT INTO uzivatel VALUES (DEFAULT, 'Jerguš', 'Chudobný','420213008', 'Mestská 222 Kežmarok', '421111444777');
INSERT INTO uzivatel VALUES (DEFAULT, 'Ivan', 'Bohatý','340608010', 'Jarná 8 Prešov', '420999666333');
INSERT INTO uzivatel VALUES (DEFAULT, 'Samuel', 'Čierny','8511250154', 'Jarná 8 Prešov', '420111222111');
INSERT INTO uzivatel VALUES (DEFAULT, 'Adam', 'Modrý','9702110253', 'Jesenná 585 Žilina', '421555444212');

--insert into host
INSERT INTO host VALUES (5, DATE '2010-10-10', 0, 'ne' );
INSERT INTO host VALUES (6, DATE '2018-01-06', 2, 'ne' );
INSERT INTO host VALUES (7, DATE '2016-08-26', 5, 'ne' );
INSERT INTO host VALUES (8, DATE '2020-12-23', 2, 'ne' );
INSERT INTO host VALUES (9, DATE '2016-05-17', 10, 'ne' );

--insert into pronajimatel
INSERT INTO pronajimatel VALUES (1, '', 'vyborna', 'minuty');
INSERT INTO pronajimatel VALUES (2, 'kontaktovat skor vopred', 'priemerna', 'hodiny');
INSERT INTO pronajimatel VALUES (3, '', 'nizka', 'dni');
INSERT INTO pronajimatel VALUES (4, '', 'priemerna', 'dni');

--insert into ubytovani
INSERT INTO ubytovani VALUES (DEFAULT, 1, 'dom','15','žiadna', 'Česko','Praha','dlhy popis','izba(2x postel), kuchynka, kuplka','zakaz fajcit vnutri','hasiaci pristroj');
INSERT INTO ubytovani VALUES (DEFAULT, 2, 'chata','50','sezonna', 'Slovensko','Michalovce','kratky popis','izby(3 x 2x postel), kuchynka, kuplka','zakaz fajcit vnutri','hasiaci pristroj, unikove schody');

SELECT * FROM uzivatel;
SELECT * FROM host;
SELECT * FROM pronajimatel;
SELECT * FROM ubytovani;

/*
CREATE TABLE ubytovani (
	ubytovani_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
	pronajimatel,
	typ VARCHAR(255) NOT NULL,
	cena INT, 
	typ_slevy VARCHAR(255),
	zeme VARCHAR(255) NOT NULL,
	mesto VARCHAR(255) NOT NULL,
	popis VARCHAR(255),
	vybaveni VARCHAR(255),
	pravidla VARCHAR(255),
	bezpecnostni_prvky VARCHAR(255),
	FOREIGN KEY (pronajimatel) REFERENCES uzivatel
);*/
